name: Deploy note
on: [push]
env:
  TZ: Asia/Shanghai
jobs:
  build: # 一项叫做build的任务
    runs-on: ubuntu-latest # 在最新版的Ubuntu系统下运行   
    steps:
    - name: Checkout # 将仓库内master分支的内容下载到工作目录
      uses: actions/checkout@v1 # 脚本来自 https://github.com/actions/checkou      
    - name: set cargo and install mdbook 
      run: |
        sudo apt-get update -y
        sudo apt-get install -y cargo
        cargo install mdbook
    - name: set env
      env:
        ACTION_DEPLOY_KEY: ${{ secrets.NOTE_DEPLOY_KEY }}
      run: |
        # set up private key for deploy
        mkdir -p ~/.ssh/
        echo "$ACTION_DEPLOY_KEY" | tr -d '\r' > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan github.com >> ~/.ssh/known_hosts
        # set git infomation
        git config --global user.name 'mikusugar' 
        git config --global user.email 'syfangjie@live.cn'
    - name: build book
      run: |
        mdbook build
        mv book ../
        git checkout page
        git pull origin
        rm -rf docs || 1
        mv ../book docs
    - name: Deploy
      run: |
        # publish
        git remote set-url origin git@github.com:MikuSugar/sugar-note.git
        git add *
        git commit -m "部署"
        git push origin
        curl https://api.day.app/jv8zA635EkHt4BTrGnNzYh/笔记更新成功～
        curl https://api.day.app/aekqRwEEdLkatYjmtVcHxZ/笔记更新成功～
