name: Deploy note
on: [push] # 当有新push时运行
env:
  TZ: Asia/Shanghai
jobs:
  build: # 一项叫做build的任务
    runs-on: ubuntu-latest # 在最新版的Ubuntu系统下运行   
    steps:
    - name: Checkout # 将仓库内master分支的内容下载到工作目录
      uses: actions/checkout@v1 # 脚本来自 https://github.com/actions/checkou      
    - name: set cargo and install mdbook 
      run: |
        sudo apt-get update -y
        sudo apt-get install -y cargo
        cargo install mdbook
    - name: set env
      env:
        ACTION_DEPLOY_KEY: ${{ secrets.NOTE_DEPLOY_KEY }} 
      run: |
        # set up private key for deploy
        mkdir -p ~/.ssh/
        echo "$ACTION_DEPLOY_KEY" | tr -d '\r' > ~/.ssh/id_rsa # 配置秘钥
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan github.com >> ~/.ssh/known_hosts
        # set git infomation
        git config --global user.name 'mikusugar' 
        git config --global user.email 'syfangjie@live.cn'
        
    - name: build book
      run: |
        cd sugar-note
        mdbook build
        mv book ../
        git checkout page
        mv ../book ./
    - name: Deploy
      run: |
        # publish
        git add *
        git commit -m "部署"
        git push origin page
        curl https://api.day.app/jv8zA635EkHt4BTrGnNzYh/博客更新成功～
        curl https://api.day.app/aekqRwEEdLkatYjmtVcHxZ/博客更新成功～
